### PR TITLE
241 unify namespace names for `type_download_ui`

### LINKED ISSUE #241: Consistent naming ID for `type_download_ui` for `table_with_settings` and `plot_with_settings`
### Feature description

Currently we have 2 similar widgets: `table_with_settings` and `plot_with_settings`. Both of them have similar structure of UI and share the same naming convention of namespaces, besides one place in `type_download_ui`

https://github.com/insightsengineering/teal.widgets/blob/3176ff54b7aef0e69528fad6dc4b6c51700c1539/R/plot_with_settings.R#L554
https://github.com/insightsengineering/teal.widgets/blob/3176ff54b7aef0e69528fad6dc4b6c51700c1539/R/table_with_settings.R#L139

Such discrepancy was caught during automated tests in https://github.com/insightsengineering/teal.widgets/pull/240

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by m7pr**
fix #241

### CODE REVIEW

**Review by gogonzo — APPROVED** [review]

**Comment by m7pr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m7pr** [comment]
recheck

**Comment by donyunardi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by donyunardi** [comment]
@gogonzo 
Can we merge this? If so, please do.

**Comment by gogonzo** [comment]
It's not worth spending time on it. I'm closing this PR as the value added of the change is minimal and PR already took too much attention

**Pull request closed without merging**
