### PR TITLE
Update DESCRIPTION before CRAN release

### PR DESCRIPTION
**Pull request by m7pr**
Continuation of https://github.com/insightsengineering/teal.widgets/pull/191 and a part of https://github.com/insightsengineering/teal.widgets/issues/189

### CODE REVIEW

**Comment by averissimo** [comment]
Wanna sneak in the update on the installation instructions on this PR? :smile: 

```diff
diff --git a/README.md b/README.md
index b3fd153..93b72d6 100644
--- a/README.md
+++ b/README.md
@@ -36,7 +36,7 @@ This package provides various widgets for `teal` applications. Examples include:
 
 ```r
 # stable versions
-install.packages('teal.widgets', repos = c('https://insightsengineering.r-universe.dev', getOption('repos')))
+install.packages('teal.widgets')
 
 # install.packages("pak")
 pak::pak("insightsengineering/teal.widgets@*release")
```

**Comment by m7pr** [comment]
@averissimo I did cross installation instructions : ) let's change them the moment the package lands on CRAN. This might take a couple more days (weeks) so let's leave installation as it is

**Review by donyunardi — APPROVED** [review]

**Comment by averissimo** [comment]
I just noticed that the side effect is that the README link on CRAN still has the r-universe way of installing :-\ https://cran.r-project.org/web/packages/teal.widgets/readme/README.html

It's not a big deal though as it will eventually be updated

**Comment by m7pr** [comment]
Oh yeah, I think the final version pushed to CRAN should have that changed manually

**Pull request merged**
