### PR TITLE
261 plot partially hidden

### LINKED ISSUE #261: [Bug]: plot partially hidden
### What happened?

Some modules display plots with a fixed width, not adjusting it to the outputs width. The plot is clipped on the right side.

This is caused by [this line](https://github.com/insightsengineering/teal.widgets/blob/afea961020573e1dfdb03371471d38e295c251f7/inst/css/plot_with_settings.css#L36), which was added for aesthetics, not funcitnoality.

Removing the line restores proper bevahior, which is adding a scroll bar.

<details> <summary> example app </summary> 

```
devtools::load_all("teal.widgets")
library(teal)
library(teal.modules.general)
library(teal.modules.clinical)

options("teal.bs_theme" = bslib::bs_theme(version = "5"))

library(nestcolor)
library(dplyr)
ADSL <- tmc_ex_adsl
ADRS <- tmc_ex_adrs %>%
  mutate(AVALC = d_onco_rsp_label(AVALC) %>%
    with_label("Character Result/Finding")) %>%
  filter(PARAMCD != "OVRINV" | AVISIT == "FOLLOW UP")
arm_ref_comp <- list(
  ARM = list(
    ref = "B: Placebo",
    comp = c("A: Drug X", "C: Combination")
  ),
  ARMCD = list(
    ref = "ARM B",
    comp = c("ARM A", "ARM C")
  )
)

app <- init(
  data = cdisc_data(
    ADSL = ADSL,
    ADRS = ADRS,
    code = "
      ADSL <- tmc_ex_adsl
      ADRS <- tmc_ex_adrs %>%
        mutate(AVALC = d_onco_rsp_label(AVALC) %>%
        with_label(\"Character Result/Finding\")) %>%
        filter(PARAMCD != \"OVRINV\" | AVISIT == \"FOLLOW UP\")
    "
  ) |>
  within(iris <- iris) |>
  within(mtcars <- mtcars) |>
  within({
    add_nas <- function(x) {
      x[sample(seq_along(x), floor(length(x) * runif(1, .05, .17)))] <- NA
      x
    }
    iris[] <- lapply(iris, add_nas)
    mtcars[] <- lapply(mtcars, add_nas)
    mtcars[["cyl"]] <- as.factor(mtcars[["cyl"]])
    mtcars[["gear"]] <- as.factor(mtcars[["gear"]])
  }),
  modules = modules(
    tm_g_forest_rsp(
      label = "Forest Response",
      dataname = "ADRS",
      arm_var = choices_selected(
        variable_choices(ADSL, c("ARM", "ARMCD")),
        "ARMCD"
      ),
      arm_ref_comp = arm_ref_comp,
      paramcd = choices_selected(
        value_choices(ADRS, "PARAMCD", "PARAM"),
        "INVET"
      ),
      subgroup_var = choices_selected(
        variable_choices(ADSL, names(ADSL)),
        c("BMRKR2", "SEX")
      ),
      strata_var = choices_selected(
        variable_choices(ADSL, c("STRATA1", "STRATA2")),
        "STRATA2"
      ),
      plot_height = c(600L, 200L, 2000L),
      default_responses = list(
        BESRSPI = list(
          rsp = c("Stable Disease (SD)", "Not Evaluable (NE)"),
          levels = c(
            "Complete Response (CR)", "Partial Response (PR)", "Stable Disease (SD)",
            "Progressive Disease (PD)", "Not Evaluable (NE)"
          )
        ),
        INVET = list(
          rsp = c("Complete Response (CR)", "Partial Response (PR)"),
          levels = c(
            "Complete Response (CR)", "Not Evaluable (NE)", "Partial Response (PR)",
            "Progressive Disease (PD)", "Stable Disease (SD)"
          )
        ),
        OVRINV = list(
          rsp = c("Progressive Disease (PD)", "Stable Disease (SD)"),
          levels = c("Progressive Disease (PD)", "Stable Disease (SD)", "Not Evaluable (NE)")
        )
      )
    ),
    tm_missing_data(
      label = "MIssing Data",
      ggplot2_args = list(
        "Combinations Hist" = ggplot2_args(
          labs = list(subtitle = "Plot produced by Missing Data Module", caption = NULL)
        ),
        "Combinations Main" = ggplot2_args(labs = list(title = NULL))
      )
    )
  )
)
shinyApp(app$ui, app$server)

```

</details>

#### before fix:
image
image

#### after fix:
image

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by chlebowa**
Fixes #261 

Removed offending line in `plot_with_settings.css`.

### CODE REVIEW

**Comment by m7pr** [comment]
Hey @chlebowa this is what I see on your branch

image

**Comment by chlebowa** [comment]
@m7pr After updating to current `teal` version, it seems the solution is to apply `overflow-x: auto`.
image

**Comment by m7pr** [comment]
@chlebowa it does fix the issue, thanks for the improvements.

However when I open other tabs, I ocassionaly see the horizontal slider even thought it's not needed

image

**Comment by chlebowa** [comment]
I cannot reproduce that one. I see you are running the app in the RStudio viewer window. Is it also there if you open the app in a browser?

**Comment by m7pr** [comment]
Ok, it's not visible in the browser :)!

**Review by m7pr — APPROVED** [review]

**Pull request merged**
