### PR TITLE
Only retain hard dependencies from pre-commit hooks

### PR DESCRIPTION
**Pull request by vedhav**
[insightsengineering/coredev-tasks/issues/471](https://github.com/insightsengineering/coredev-tasks/issues/471)

Screenshot 2023-08-29 at 2 15 55 PM

### CODE REVIEW

**Review by donyunardi — CHANGES_REQUESTED** [review]
Tried to trigger the hooks and I got some warnings:


I think we need to add `rtables`.

**Comment by vedhav** [comment]
Thanks for catching this @donyunardi. Since we are using `rtables` inside the package functions it should be an `Imports` dependency in the `DESCRIPTION` file too right?

**Comment by pawelru** [comment]
> Thanks for catching this @donyunardi. Since we are using `rtables` inside the package functions it should be an `Imports` dependency in the `DESCRIPTION` file too right?

See https://github.com/insightsengineering/teal.widgets/issues/154. Let me also summon @m7pr who analysed this already.

**Comment by m7pr** [comment]
Hey, commented in #154 . Having second thoughts, I would bring back `rtables` to Imports. I never had any strong preference towards any approach (`Suggests` nor `Imports`) but it looks like `rtables` is used in 3 functions, and this `Suggests` trick is bringing more issues than it actually helps.

**Review by donyunardi — APPROVED** [review]
LGTM!
image

I'm approving this but can you please add NEWS.md to show that we're moving rtables back to Imports?

**Pull request merged**
